### ISSUE TITLE
Not displaying correclty on fire tv stick

### ISSUE THREAD

**Issue by faintuk** [ngovil21/PlexRequestChannel.bundle#23]
When selecting the channel I can only see 4 options, View Requests, Manage Sonnar, Report a Problem and Manage Channel,

I have no issues when using the channel on my nexus 5 phone

**Comment by ngovil21** [comment]
Would you be able to PM the log on the Plex Forums? Alternatively if you can look at the log and tell me what it says for Platform and Client when the FireTV accesses the channel, I'll be able to work on a fix.

**Comment by j4m** [comment]
Access from AFTV 1 produces the following log entries:

> Platform: Android
> Product: Plex for Android
> Accept-Language: en

**Comment by ngovil21** [comment]
Well that's a problem, so it looks like the AFTV1 identifies itself as an android client, but behaves differently from the Android client with regard to input objects.

My fix will be to add a toggle to switch to the alternate keyboard from the Main Menu. This will need to be done every time the channel is accessed on the AFTV. Otherwise I would remove the input support from other Android devices as there is no way for the channel to differentiate between the two clients.

This may cause confusion with other people, but we'll see.
